"""Build Jekyll content and a directly viewable HTML site from one data file."""
import json
import re
import shutil
from html import escape
from pathlib import Path
import yaml
from jinja2 import Environment, StrictUndefined
from markupsafe import Markup

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "html_source_file"
profile = json.loads((ROOT / "_data/profile.json").read_text(encoding="utf-8"))
unavailable = set(profile.get("unavailable_links", []))

def available_links(record):
    return [url for url in record["links"] if url not in unavailable]

def links(record):
    label = escape("Open link: " + record["text"], quote=True)
    icon = '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M15 3h6v6M10 14 21 3M21 14v7H3V3h7"/></svg>'
    return " ".join(f'<a class="record-link" href="{escape(url, quote=True)}" title="Open link" aria-label="{label}">{icon}</a>' for url in available_links(record))

def section(section_id, title, body):
    return f'<section id="{section_id}" class="content-section" aria-labelledby="{section_id}-title">\n<h2 id="{section_id}-title">{title}</h2>\n{body}\n</section>\n'

def record_list(records, kind="plain"):
    rows = []
    for record in records:
        text = record["text"]
        if kind == "dated":
            match = re.match(r"^(\d{4}) (.*)$", text)
            date, title = match.groups() if match else ("", text)
            body = f'<span class="record-year">{escape(date)}</span><div><span>{escape(title)}</span> {links(record)}</div>'
        elif kind == "project":
            match = re.match(r"^(.*?)\s*\((.*?)\)\s*$", text)
            title, date = match.groups() if match else (text, "")
            body = f'<h4>{escape(title)}</h4><div class="record-meta">{escape(date)} {links(record)}</div>'
        else:
            body = f'<span>{escape(text)}</span> {links(record)}'
        rows.append(f'<li class="record">{body}</li>')
    return f'<ul class="record-list {kind}-list">' + "\n".join(rows) + "</ul>"

parts = [section("about", "About Me", f'<p class="intro">{escape(profile["about"])}</p>')]
research = profile["research"]
tags = "".join(f'<li>{escape(item)}</li>' for item in research["interests"])
research_paper = escape(research["paper_label"])
if research["paper_url"] not in unavailable:
    research_paper = f'<a href="{escape(research["paper_url"])}">{research_paper} <span aria-hidden="true">↗</span></a>'
parts.append(section("research", "Research Interests", f'''<ul class="research-topics">{tags}</ul>
<p><strong>Recent:</strong> {escape(research['recent'])}</p>
<p><strong>Previous:</strong> {escape(research['previous'])}</p>
<p class="research-paper"><strong>Paper:</strong> {research_paper}</p>'''))
education = []
for item in profile["education"]:
    detail = f'<span class="education-detail">{escape(item["detail"])}</span>' if item["detail"] else ""
    education.append(f'''<li class="education-item"><h3>{escape(item['institution'])}</h3>
<p>{escape(item['program'])} · {escape(item['location'])}</p>
<p class="record-meta">{escape(item['dates'])} {detail}</p></li>''')
parts.append(section("education", "Education", '<ul class="education-list">' + "".join(education) + "</ul>"))
papers = []
for index, paper in enumerate(profile["publications"], 1):
    title = escape(paper["text"])
    if available_links(paper):
        title = f'<a href="{escape(available_links(paper)[0])}">{title}</a>'
    papers.append(f'<li class="publication"><span class="publication-number" aria-hidden="true">{index:02d}</span><div><h3>{title}</h3>{links(paper)}</div></li>')
parts.append(section("publications", "Publications", '<ol class="publication-list">' + "\n".join(papers) + "</ol>"))
parts.append(section("projects", "Projects", '<h3 class="subheading">ROS Projects</h3>' + record_list(profile["robotics_projects"], "project") + '<h3 class="subheading">Web Projects</h3>' + record_list(profile["web_projects"], "project")))
parts.append(section("awards", "Awards", record_list(profile["awards"], "dated")))
parts.append(section("activities", "External Activities", record_list(profile["activities"], "dated")))
parts.append(section("skills", "Skills", '<h3 class="subheading">Professional Programming Skills</h3>' + record_list(profile["programming_skills"]) + '<h3 class="subheading">English Skills</h3>' + record_list(profile["english_skills"])))
content = "\n".join(parts)
(ROOT / "index.md").write_text("---\nlayout: homepage\n---\n\n<!-- Generated by scripts/build_site.py from _data/profile.json. -->\n\n" + content, encoding="utf-8")
config = yaml.safe_load((ROOT / "_config.yml").read_text(encoding="utf-8"))
config.update({
    "title": profile["name"], "position": profile["department"], "affiliation": profile["affiliation"],
    "email": profile["email"], "github_link": profile["github"], "avatar": "assets/img/profile.jpg",
    "cv_link": profile.get("cv", ""),
    "google_scholar": profile.get("google_scholar", ""),
    "description": f"{profile['name']} — Robotic manipulation, data collection systems, and sim-to-real at Kongju National University.",
    "keywords": f"{profile['name']}, Kongju National University, robotic manipulation, data collection systems, sim-to-real",
    "lang": "en", "enable_footnote": True, "auto_dark_mode": True, "font": "Serif", "baseurl": config.get("baseurl", ""),
    "exclude": ["Gemfile", "Gemfile.lock", "README.md", "README_de.md", "README_zh_Hans.md", "README_zh_Hant.md", "LICENSE", "html_source_file", "scripts", "requirements.txt"]
})
for key in ["google_analytics", "linkedin", "twitter", "favicon", "favicon_dark", "remote_theme"]:
    config.pop(key, None)
if config.get("canonical") == "https://minimal-light-theme.yliu.me/":
    config.pop("canonical")
(ROOT / "_config.yml").write_text(yaml.safe_dump(config, allow_unicode=True, sort_keys=False), encoding="utf-8")
env = Environment(autoescape=True, undefined=StrictUndefined)
env.filters["escape"] = lambda value: Markup(escape(str(value), quote=True))
env.filters["relative_url"] = lambda value: "./" + str(value).lstrip("/")
site = dict(config, data={"profile": profile})
site.setdefault("canonical", "")
layout = env.from_string((ROOT / "_layouts/homepage.html").read_text(encoding="utf-8"))
OUT.mkdir(exist_ok=True)
rendered = layout.render(site=site, content=Markup(content))
(OUT / "index.html").write_text("\n".join(line.rstrip() for line in rendered.splitlines()) + "\n", encoding="utf-8")
for relative in ["assets/css/profile.css", "assets/css/font.css", "assets/js/navigation.js", "assets/img/profile.jpg", "assets/img/monogram.svg"]:
    target = OUT / relative
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(ROOT / relative, target)
if profile.get("cv"):
    cv_path = Path(profile["cv"])
    if cv_path.is_absolute() or ".." in cv_path.parts:
        raise ValueError("CV must be a relative path inside the website.")
    target = OUT / cv_path
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(ROOT / cv_path, target)
(OUT / ".nojekyll").touch()
shutil.copy2(ROOT / "LICENSE", OUT / "LICENSE")
print(f"Built {OUT / 'index.html'}")
print(f"Records: {len(profile['publications'])} publications, {len(profile['robotics_projects']) + len(profile['web_projects'])} projects, {len(profile['awards'])} awards, {len(profile['activities'])} activities.")
